master:
  build: .
  image: herzogf/rpi-jenkins:latest
  environment:
    JAVA_OPTS: "-Djava.awt.headless=true"
  ports:
    - "50000:50000"
    - "8080:8080"
  volumes:
    - ../rpi-jenkins-data:/var/jenkins_home
